### ISSUE TITLE
widget calendar

### ISSUE THREAD

**Issue by dphengsiaroun** [dphengsiaroun/logistic#19]

**Comment by jlguenego** [comment]
- traiter les heures
- animation pour les heures
- traiter le angular-touch

**Comment by jlguenego** [comment]
marquer l'heure dans le titre quand selectionné, puis inviter à  cliquer sur check pour sélectionner l'heure.

**Comment by dphengsiaroun** [comment]
contrainte sur dates antérieures

**Comment by dphengsiaroun** [comment]
fait
