### ISSUE TITLE
ville algerie

### ISSUE THREAD

**Issue by jlguenego** [dphengsiaroun/logistic#40]
- faire une liste accessible en asynchrone
- downloader la liste une fois le minimum downloadé.
- prendre la liste en json sur un site (au moins sur wikipedia)

ne faire que l'algérie pour l'instant.

**Comment by dphengsiaroun** [comment]
Faire un widget input type = city avec la géolocalisation. Voir comment faire pour utiliser le gps du téléphone ou navigateur

**Comment by jlguenego** [comment]
ne pas oublier de faire un popup quand le geoloc n'est pas activé : faire une petite doc pour expliquer comment faire.

**Comment by dphengsiaroun** [comment]
fait
